package by.tc.web.controller;

public enum CommandName {
    AUTHORIZATION, REGISTRATION, FILL_PAGE_INDEX, LOCALIZATION, EXIT_USER,
    FILL_PAGE_FILMS, FILL_PAGE_FILM, LOCALIZATION_PAGE_FILM, MARK,FILL_ADMIN_MENU, ADD_FILM,
    EDIT_FILM, DELETE_FILM, ADD_USER,EDIT_USER,DELETE_USER, DELETE_COMMENT,BAN_USER,EDIT_PROFILE,
    LOAD_PROFILE, SEARCH
}
